# Generated by Django 5.2.7 on 2025-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
