# Generated by Django 4.2.25 on 2025-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_estudiante_edad_estudiante_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_acu', models.AutoField(primary_key=True, serialize=False)),
                ('num_doc_acu', models.CharField(max_length=20)),
                ('tel_acu', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_acu', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acudiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_adm', models.AutoField(primary_key=True, serialize=False)),
                ('num_doc_adm', models.CharField(max_length=20)),
                ('tel_adm', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_adm', models.CharField(blank=True, max_length=100, null=True)),
                ('tip_carg_adm', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_cur', models.AutoField(primary_key=True, serialize=False)),
                ('grd_cur', models.CharField(max_length=10)),
                ('num_alum_cur', models.IntegerField(blank=True, null=True)),
                ('cup_disp_cur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('reg_civil_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_idn_acu', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_idn_alum', models.CharField(blank=True, max_length=100, null=True)),
                ('cnt_vac_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('adres_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('fot_alum_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_extr_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('cer_med_disca_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('cer_esc_doc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_inst', models.AutoField(primary_key=True, serialize=False)),
                ('nom_inst', models.CharField(max_length=100)),
                ('tip_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_dane_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('dep_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('mun_inst', models.CharField(blank=True, max_length=50, null=True)),
                ('dire_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_inst', models.CharField(blank=True, max_length=20, null=True)),
                ('ema_inst', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('fch_reg_mat', models.DateField()),
                ('est_mat', models.CharField(blank=True, max_length=20, null=True)),
                ('obs_mat', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=50)),
                ('ape_usu', models.CharField(max_length=50)),
                ('ema_usu', models.CharField(max_length=100, unique=True)),
                ('con_usu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False},
        ),
    ]
