# Generated by Django 4.2.25 on 2025-10-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_acudiente_administrativo_curso_documento_institucion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
    ]
